name: smash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  cloud_firestore: ^4.9.2
  equatable: ^2.0.5
  firebase_core: ^2.16.0
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
    - lib/ui/assets/animations/
  fonts:
    - family: Lexend
      fonts:
        - asset: lib/ui/assets/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: lib/ui/assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: lib/ui/assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: lib/ui/assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: lib/ui/assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: lib/ui/assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: lib/ui/assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: lib/ui/assets/fonts/Lexend-ExtraBold.ttf
          weight: 800